### ISSUE TITLE
here's another set of unrecognized VU0 instructions

### ISSUE THREAD

**Issue by modusc896d352** [chaoticgd/ghidra-emotionengine-reloaded#42]
came across another set of what seems to be unrecognized VU0 instructions (four of them it seems)
![VU0 instructions that failed to disassemble for some reason.](https://files.catbox.moe/9mmdbr.png)

and here are the error messages that they trigger
![Unable to resolve constructor at 00262a30 (flow from 00262a2c)](https://files.catbox.moe/141ld4.png)
![Unable to resolve constructor at 00262a34](https://files.catbox.moe/w7x3iy.png)
![Unable to resolve constructor at 00262a54 (flow from 00262a50)](https://files.catbox.moe/aubk44.png)
![Unable to resolve constructor at 00262a58](https://files.catbox.moe/4c7ajv.png)

apologies for the lack of details

**Comment by chaoticgd** [comment]
I've figured out what the problem is: there was a missing instruction.

Can you test out this unstable build for me? https://github.com/chaoticgd/ghidra-emotionengine-reloaded/releases/download/unstable/ghidra_10.3.3_PUBLIC_20231004_ghidra-emotionengine-reloaded.zip

Edit: Or https://github.com/chaoticgd/ghidra-emotionengine-reloaded/releases/download/unstable/ghidra_10.4_PUBLIC_20231004_ghidra-emotionengine-reloaded.zip

**Comment by modusc896d352** [comment]
OK, time for me to test your new build.

**Comment by modusc896d352** [comment]
OK, tested your new build and will you look at that...
![](https://files.catbox.moe/5u39l4.png)
missing instructions are no longer missing!
thanks for the update!
