### ISSUE TITLE
Provide releases for multiple Ghidra versions

### ISSUE THREAD

**Issue by antoniovazquezblanco** [chaoticgd/ghidra-emotionengine-reloaded#78]
Hi, I am working on a Ghidra extension that is able to install other extensions from Github (https://github.com/antoniovazquezblanco/GhidraExtensionManager).

Currently, this extension is only released targetting the latest Ghidra release available but it has the infraestructure to provide releases for multiple versions.

Would you be willing to include multiple Ghidra version support in your pipelines?

Thanks!

**Comment by chaoticgd** [comment]
So far I've only been supporting a single version per release in order to reduce the amount of testing required.

When the next release of Ghidra comes out I could add support for multiple versions, but only if no code changes are required, in which case there may not be much benefit to it since new Ghidra versions tend to come out more frequently than I add new features to this extension.

**Comment by chaoticgd** [comment]
The last big change was Ghidra 11.1, where they rewrote their relocation system and I had to update the extension to match.

**Comment by chaoticgd** [comment]
The new release supports two versions.
