### ISSUE TITLE
"Address not in memory"

### ISSUE THREAD

**Issue by Kneesnap** [chaoticgd/ghidra-emotionengine-reloaded#81]
Heya! I've got a game SLES_507.88 (Frogger: The Great Quest PS2 PAL) which has a portion (portions?) of address space which do not appear to be handled properly by Ghidra/this extension.

![image](https://github.com/user-attachments/assets/8f386cc8-816f-41ba-ae2d-bac17bf5aeec)
![image](https://github.com/user-attachments/assets/14e302bf-8c8b-435e-996e-59050150a50d)

Every symbol Ghidra highlights in yellow (excluding local vars) here is one which is impacted by this issue. (This impacts a large portion of the game's global data.) An example of a symbol not impacted here is 'pAISystem'.

I'm not entirely sure the root cause of this issue, but if possible it'd be nice to be fixed. Thanks! =)

EDIT: Yes I am aware the structs don't look right here, this can be ignored, it's not relevant.

**Comment by Kneesnap** [comment]
Actually, here's another example of another manifestation of this issue:
![image](https://github.com/user-attachments/assets/d3b0c426-437d-4f6d-b154-2faa87184fcb)

**Comment by chaoticgd** [comment]
It looks like the problem is the .bss section isn't included in the ELF's section headers. You can remedy this by opening the memory map dialog in Ghidra and adding it yourself. If you look at the entry point for the ELF it's got a loop that zeroes the .bss section, so you can use that to determine its bounds. In this case it looks like it starts at 0x222a00 and ends at 0x440000.

![Screenshot_20241104_235626](https://github.com/user-attachments/assets/fa3961a2-8fb6-4e23-8b3e-a8302dbe84a3)

**Comment by chaoticgd** [comment]
Actually it may make sense to select 'Initialized' in the dialog above, since it's .bss.

**Comment by Kneesnap** [comment]
Perfect, I thought it was going to be more complicated for some reason, but this does appear to have fixed the issue.
